services:
  redis-6381:
    image: redis:6.2.6-alpine
    container_name: redis-6381
    ports:
      - "6381:6379"
    command: redis-server --requirepass ${HMDP_REDIS_PASSWORD:-change-me} --appendonly yes
    volumes:
      - redis-6381-data:/data

  redis-6382:
    image: redis:6.2.6-alpine
    container_name: redis-6382
    ports:
      - "6382:6379"
    command: redis-server --requirepass ${HMDP_REDIS_PASSWORD:-change-me} --appendonly yes
    volumes:
      - redis-6382-data:/data

  rabbitmq:
    image: rabbitmq:4.3.4-management
    container_name: hmdp-rabbitmq
    hostname: hmdp-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${HMDP_RABBITMQ_USERNAME:-hmdp}
      RABBITMQ_DEFAULT_PASS: ${HMDP_RABBITMQ_PASSWORD:-hmdp_mq_2026}
      RABBITMQ_DEFAULT_VHOST: ${HMDP_RABBITMQ_VIRTUAL_HOST:-/hmdp}
      TZ: Asia/Shanghai
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-6381-data:
  redis-6382-data:
  rabbitmq-data:
